spring:
    datasource:
        url: jdbc:mysql://10.100.50.98:3306/microservices
        username: root
        password: Accenture@123
        driver-class-name: com.mysql.jdbc.Driver
confirm:
    order:
        request:
          queue: confirmedOrderQueue
          routingKey : confirmOrderRoutingKey
        response:
          queue : confirmOrderResponseQueue2
          routingKey : confirmOrderResponseRoutingKey

cancel:
  order:
    queue: cancelledOrderQueue
    routingKey : cancelOrderRoutingKey


routing:
  key : fixedRoutingKey

dead:
    letter:
        queue:
            name: deadLetterQueue

server:
  port : 5020

queue:
  name : microserviceAppQueue

exchange:
  name : orderToInventoryExchange